#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "PYFILE env variable is not set"
    exit 1
fi

py_file="$PYFILE"

if [ ! -f "$py_file" ]; then
    echo "'$py_file' is not found"
    exit 1
fi

python3 "$py_file"
